# Neon DB Connection URL
db_url = "postgresql://DB_OWNER:DB_PASSWORD@DB_HOST/neondb?sslmode=require"

# Admin credentials
[admin_credentials]
email = "admin@example.com"
password = "adminpassword"
